config/routes.rb
Rails.application.routes.draw do
  ##Below will generate the CRUD for auction_lists controller
  resources :auction_lists
  
  ##Routes for upload form 
  get 'upload', to: 'auction_lists#upload_form'

  ##Routes for post of the upload form
  post 'import', to: 'auction_lists#import'

  ##Routes for the root method
  root :to => "auction_lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auction_list.rb
class AuctionList < ApplicationRecord
   require 'csv'

   scope :ordered_by_created_at, -> { reorder(created_at: :asc) }

   private
   
   ## Import the uploaded file into the database 
   def self.import(file)
      csv_text = File.read(file.path)
      csv = CSV.parse(csv_text, :headers => true)
      csv.each do |row|
        AuctionList.create!(row.to_hash)
      end
   end

   ## Get total_profit, avg profit per vehicle for each of the auctions
   ## Only one query is triggered to calculate the output

   def self.get_auction_count 
     @auction_count= AuctionList.select("name as auction_name, count(name) as count, (sum(winning_bid)-sum(seller_payout)) as total_profit, (sum(winning_bid)-sum(seller_payout))/count(name) as avg_profit").group("name").ordered_by_created_at
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/auction_lists_controller.rb
class AuctionListsController < ApplicationController
  before_action :set_auction_list, only: [:show, :edit, :update, :destroy]

  # GET /auction_lists
  # GET /auction_lists.json
  # get_auction_count method is defined in model 
  # in order to keep the controller skinny

  def index
    @auction_lists = AuctionList.all
    @auction_count = AuctionList.get_auction_count
  end


  ## GET /upload
  ## This method render the default upload form 
  ## for importing the auction data from csv file

  def upload_form
    render :upload_form
  end

  ## POST /import
  ## This action is invoked with the form submit
  ## of the upload form
  ## On success it will be redirected to show all the auctions
  
  ##This method will invoke the models method import 
  ## which will load the file into the database
  def import
     file = params[:file]
     ##If upload is not successful then render to the same page 
     ## with flash message
     begin
        AuctionList.import(file)
        redirect_to root_url, notice: "Successfully added the data"
     rescue => e
        flash.now[:notice] = "Can't import the file:  #{e.message}"
        render  :upload_form
     end
  end

  # GET /auction_lists/1
  # GET /auction_lists/1.json
  def show
  end

  # GET /auction_lists/new
  def new
    @auction_list = AuctionList.new
  end

  # GET /auction_lists/1/edit
  def edit
  end

  # POST /auction_lists
  # POST /auction_lists.json
  def create
    @auction_list = AuctionList.new(auction_list_params)

    respond_to do |format|
      if @auction_list.save
        format.html { redirect_to @auction_list, notice: 'Auction list was successfully created.' }
        format.json { render :show, status: :created, location: @auction_list }
      else
        format.html { render :new }
        format.json { render json: @auction_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auction_lists/1
  # PATCH/PUT /auction_lists/1.json
  def update
    respond_to do |format|
      if @auction_list.update(auction_list_params)
        format.html { redirect_to @auction_list, notice: 'Auction list was successfully updated.' }
        format.json { render :show, status: :ok, location: @auction_list }
      else
        format.html { render :edit }
        format.json { render json: @auction_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auction_lists/1
  # DELETE /auction_lists/1.json
  def destroy
    @auction_list.destroy
    respond_to do |format|
      format.html { redirect_to auction_lists_url, notice: 'Auction list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auction_list
      @auction_list = AuctionList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auction_list_params
      params.require(:auction_list).permit(:name, :city, :vehicle, :winning_bid, :seller_payout)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auction_lists_helper.rb
module AuctionListsHelper
end

app/views/auction_lists/_form.html.erb
<%= form_for(auction_list) do |f| %>
  <% if auction_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(auction_list.errors.count, "error") %> prohibited this auction_list from being saved:</h2>

      <ul>
      <% auction_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :vehicle %>
    <%= f.text_field :vehicle %>
  </div>
  <div class="field">
    <%= f.label :seller_payout %>
    <%= f.text_field :seller_payout%>
  </div>
  <div class="field">
    <%= f.label :winning_bid %>
    <%= f.text_field :winning_bid %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/auction_lists/edit.html.erb
<h1>Editing Auction List</h1>

<%= render 'form', auction_list: @auction_list %>

<%= link_to 'Show', @auction_list %> |
<%= link_to 'Back', auction_lists_path %>

app/views/auction_lists/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Auction List</h1>

<table>
  <thead>
    <tr>
      <th>Auction Name</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auction_lists.each do |auction_list| %>
      <tr>
        <td><%= auction_list.name %></td>
        <td><%= auction_list.city %></td>
        <td><%= link_to 'Show', auction_list %></td>
        <td><%= link_to 'Edit', edit_auction_list_path(auction_list) %></td>
        <td><%= link_to 'Destroy', auction_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h1>Auction Details</h1>

  <table>
  <thead>
    <tr>
       <th>Auction Name</th>
       <th>Vehicles Sold</th>
       <th>Avg Profit</th>
       <th>Total Profit</th>
    </tr>
   </thead>
   </tbody>
    <% @auction_count.each do |ac| %>
      <tr>
        <td><%= ac.auction_name %></td>
        <td><%= ac.count %></td>
        <td><%= number_with_precision(ac.avg_profit, :precision => 2) || 0 %></td>
        <td><%= number_with_precision(ac.total_profit, :precision => 2) || 0 %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
</br>
<%= link_to 'Import Auction List', action: 'upload_form' %>

app/views/auction_lists/new.html.erb
<h1>New Auction List</h1>

<%= render 'form', auction_list: @auction_list %>

<%= link_to 'Back', auction_lists_path %>

app/views/auction_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @auction_list.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @auction_list.city %>
</p>
<p>
  <strong>Vehicle:</strong>
  <%= @auction_list.vehicle%>
</p>

<p>
  <strong>Winning Bid:</strong>
  <%= @auction_list.winning_bid%>
</p>

<p>
  <strong>Seller Payout:</strong>
  <%= @auction_list.seller_payout%>
</p>

<%= link_to 'Edit', edit_auction_list_path(@auction_list) %> |
<%= link_to 'Back', auction_lists_path %>

app/views/auction_lists/upload_form.html.erb
<font size="4" color="red"><b><%= notice %></b></font>
<h1 style="text-align: center;"> Auction Upload Form </h1>
</br>
</br>
<%= form_tag({:action => :import}, multipart: true) do %>
  <label> Upload File:  </label> 
    <%= file_field_tag :file, :accept => 'text/csv' %>
  </br>
  </br>
  <div ><%= submit_tag( "Import" ) %> </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auction</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>